[package]
name = "jsqlf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tree-sitter = "0.20.8"
tree-sitter-jsql = { path = "tree-sitter-jsql"}

[dev-dependencies]
indoc = "1.0"
